name: CI/CD - react

on:
  push:
    branches:
      - react

jobs:
  build:
    name: Build, lint on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: ❇️ Checkout repo
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 📥 Install dependencies with Bun (with cache)
        run: |
          if [ -d packages/supabase-kit-react ]; then
            ls packages/supabase-kit-react
            bun install --cwd packages/supabase-kit-react
          else
            echo "Directory packages/supabase-kit-react not found!"
            exit 1
          fi

      - name: 💅 Lint
        run: |
          if [ -d packages/supabase-kit-react ]; then
            cd packages/supabase-kit-react/ && bun lint
          else
            echo "Directory packages/supabase-kit-react not found!"
            exit 1
          fi

      # - name: 🧪 Test
      #   run: bun test --ci --coverage --max-workers=2

      - name: 🛠️ Build
        run: |
          if [ -d packages/supabase-kit-react ]; then
            cd packages/supabase-kit-react/ && bun run build
          else
            echo "Directory packages/supabase-kit-react not found!"
            exit 1
          fi

      - name: 🚀 Publish to npm
        run: |
          ls packages/supabase-kit-react
          if [ -f packages/supabase-kit-react/package.json ]; then
            npx npm-publish --package packages/supabase-kit-react/package.json --token ${{ secrets.NPM_TOKEN }}
          else
            echo "package.json not found!"
            exit 1
          fi
